import 'package:rehab_flutter/core/entities/song.dart';
import 'package:rehab_flutter/core/enums/genre_enum.dart';

class SongProvider {
  static List<Song> songs = [
    Song(
      title: "VivaLaVida",
      artist: "Coldplay",
      audioSource: 'audio/vivalavida.mp3',
      genre: Genre.pop,
      tempo: 135.99917763,
      duration: 242.10290249433106,
      metaDataUrl: 'assets/data/vivalavida.json',
    ),
    Song(
      title: "Forest Of Blocks",
      artist: "Confei Wei",
      audioSource: 'audio/forestofblocks.mp3',
      genre: Genre.classical,
      tempo: 83.35433468,
      duration: 73.67691609977324,
      metaDataUrl: 'assets/data/forestofblocks.json',
    ),
    Song(
      title: "Entry of the Gladiators",
      artist: "Julius Fucik",
      audioSource: 'audio/entryofthegladiators.mp3',
      metaDataUrl: 'assets/data/entryofthegladiators.json',
      genre: Genre.classical,
      tempo: 112.34714674,
      duration: 175.29578231292518,
    ),
    Song(
      title: "Swan Lake",
      artist: "Pyotr Ilyich Tchaikovsky",
      audioSource: 'audio/swanlake.mp3',
      metaDataUrl: 'assets/data/swanlake.json',
      genre: Genre.classical,
      tempo: 129.19921875,
      duration: 175.12494331065759,
    ),
    Song(
      title: "Ode To Joy",
      artist: "Ludwig van Beethoven",
      audioSource: 'audio/odetojoy.mp3',
      metaDataUrl: 'assets/data/odetojoy.json',
      genre: Genre.classical,
      tempo: 135.99917763,
      duration: 264.4520634920635,
    ),
    Song(
      title: "Canon in D",
      artist: "Johann Pachelbel",
      audioSource: 'audio/canon.mp3',
      genre: Genre.classical,
      metaDataUrl: "assets/data/canon.json",
      tempo: 143.5546875,
      duration: 170.55056689342405,
    ),
    Song(
      title: "Fur Elise",
      artist: "Ludwig van Beethoven",
      audioSource: 'audio/furelise.mp3',
      metaDataUrl: 'assets/data/furelise.json',
      genre: Genre.classical,
      tempo: 143.5546875,
      duration: 173.0118820861678,
    ),
    Song(
      title: "Cancan",
      artist: "Jacques Offenbach",
      audioSource: 'audio/cancan.mp3',
      metaDataUrl: "assets/data/cancan.json",
      genre: Genre.classical,
      tempo: 161.49902344,
      duration: 142.61696145124716,
    ),
    Song(
      title: "Flight of the Bumblebee",
      artist: "Nikolai Rimsky-Korsakov",
      audioSource: 'audio/flightofthebumblebee.mp3',
      metaDataUrl: 'assets/data/flightofthebumblebee.json',
      genre: Genre.classical,
      tempo: 161.49902344,
      duration: 105.60439909297052,
    ),
    Song(
      title: "Moonlight Sonata",
      artist: "Ludwig van Beethoven",
      audioSource: 'audio/moonlightsonata3rdmovement.mp3',
      metaDataUrl: 'assets/data/moonlightsonata3rdmovement.json',
      genre: Genre.classical,
      tempo: 172.265625,
      duration: 407.8900680272109,
    ),
    Song(
      title: "Waltz of the Flowers",
      artist: "Pyotr Ilyich Tchaikovsky",
      audioSource: 'audio/waltzoftheflowers.mp3',
      metaDataUrl: 'assets/data/waltzoftheflowers.json',
      genre: Genre.classical,
      tempo: 172.265625,
      duration: 482.68485260770973,
    ),
  ];
}
